### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [Botfaqtor/gtm_template#1]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on data.siteId when generating the url
const url = 'https://scripts.witstroom.com/one/' + data.siteId + '?' + generateRandom(1, 99999);

**Comment by maksim-nzr** [comment]
Thank you for the correction. EncodeUriComponent added.
